# The function of this r script is init the analysis enviorment.
# 1. Loading the necessary packages
# 2. Loading some functions to extract data from the presentation 
#    log files


library(tidyverse)

#' @title mark_replacer
#' @description If you need to change the code in the presentation
#'              logfile in a batch way, you need this function.
#' @param all_logfile_path The path contains all of the logfiles.
#' @param rule An csv file. In this table, the first column is
#'             the pattern, and the second line is the replacement.
#' @return A set of logfile with correct code. Their file name will
#'         end with "correct_mark".
#' @details Some times I have write wrong code in my programme.
#' @rdname mark_replacer
#' @importFrom stringr str_replace
mark_replacer <- function(all_logfile_path, rule = NA) {
  library(stringr)
  all_filenames <- dir(all_logfile_path, full.names = T)
  all_filenames <- all_filenames[str_detect(all_filenames, ".log")]
  all_filenames <- all_filenames[!str_detect(all_filenames, "logfile.R")]
  all_filenames <- all_filenames[!str_detect(all_filenames, "_correct_mark.log")]
  
  if (is.na(rule)) {
    rule <- file.choose()
  }
  rule <- read.csv(rule, header = F, sep = "\t")
  
  tiny_replacer <- function(logfile, rule) {
    foo <- readLines(logfile)
    for (i in 1:nrow(rule)) {
      foo <- stringr::str_replace(foo, pattern = as.character(rule[i, 1]), replacement = as.character(rule[i, 2]))
    }
    new_filename <- str_replace(logfile, ".log", "_correct_mark.log")
    writeLines(foo, con = new_filename)
  }
  
  for (i in all_filenames) {
    tiny_replacer(i, rule)
  }
}

#' @title read_logfile_to_dataframe
#' @description This function could read the logfile and transform
#'              it to a data frame which contain the RT information
#' @param logfile The logfile generated by Presentation, Default: NA
#' @return A data frame of the RT infromation
#' @details Extract the RT table in logfile
#' @seealso
#'  \code{\link[stringr]{str_detect}}
#' @rdname read_logfile_to_dataframe
#' @export
#' @importFrom stringr str_detect
read_logfile_to_dataframe <- function(logfile = NA, end_code = "end_message") {
  if (is.na(logfile)) {
    logfile <- file.choose()
  }
  
  temp_text_file <- readLines(logfile)
  
  index_message <- which(stringr::str_detect(temp_text_file, "Subject"))[[1]]
  end_message <- which(stringr::str_detect(temp_text_file, end_code))[[1]]
  index_RT <- which(stringr::str_detect(temp_text_file,"RT"))[[1]]
  
  
  message_table <- read.delim(textConnection(temp_text_file[(index_message):(end_message+2)]), sep = "\t") %>% 
    filter(Event.Type == "Picture") %>% 
    select(Subject, Trial)
  RT_table <- read.csv(textConnection(c(temp_text_file[index_RT], temp_text_file[(index_RT + 2):length(temp_text_file)])), sep = "\t")%>% 
    filter(Event.Type == "Picture")
  
  RT_table$RT <- RT_table$RT / 10
  
  return(cbind(RT_table, message_table))
}

#' @title Results_Stat_Ratio_extractor
#' @description This function can extract the result from
#'              the Results_Stat_Ratio.csv file.
#' @param Results_Stat_Ratio_EEG Results_Stat_Ratio.csv
#'                               created by lingwang's script.
#' @param block The block matched to the csv file.
#' @return A dataframe contain the RT and error rate.
#' @details This function can extract the result from the
#'          Results_Stat_Ratio.csv which created by Lingwang's
#'          ling_Behavior_fMRI_Analysis.m script.
#' @rdname Results_Stat_Ratio_extractor
#' @export
#' @importFrom stringr str_detect
#' @importFrom dplyr select_if
#'
Results_Stat_Ratio_extractor <- function(Results_Stat_Ratio_EEG = NA, block) {
  require(magrittr)
  
  if (is.na(Results_Stat_Ratio_EEG)) {
    Results_Stat_Ratio_EEG <- file.choose()
  }
  
  temp_file_lines <- readLines(Results_Stat_Ratio_EEG)
  
  index_RT <- which(stringr::str_detect(
    temp_file_lines,
    "RT WITHOUT outliers"
  ))
  index_RT_end <- which(stringr::str_detect(
    temp_file_lines,
    "RT - Median"
  ))
  index_error_rate <- which(stringr::str_detect(
    temp_file_lines,
    "Error rate"
  ))
  
  RT_table <- temp_file_lines[(index_RT + 2):(index_RT_end - 3)] %>%
    textConnection() %>%
    read.csv() %>%
    cbind(type = "RT", block = block) %>%
    dplyr::select_if(~ !all(is.na(.))) # 删除全部为NA的列
  
  error_table <- temp_file_lines[(index_error_rate + 2):
                                   length(temp_file_lines)] %>%
    textConnection() %>%
    read.csv() %>%
    cbind(type = "error_rate", block = block) %>%
    dplyr::select_if(~ !all(is.na(.)))
  
  output_table <- rbind(RT_table, error_table)
  return(output_table)
}

#' @title sep_logfile
#' @description This function can separate the presentation logfile
#'              which contains whole data of the experiment to a set
#'              of files by blocks.
#' @param filename A presentation logfile which contains data of
#'                 whole experiment.
#' @param block_names A vector composed by the name of each block.
#'                    e.g.  c("block1", "block2", "block3", "block4")
#' @return A set of presentation logfiles separated by blocks.
#' @details For my habit of experiment.
#' @rdname sep_logfile
#' @export
#' @importFrom stringr str_detect str_replace
sep_logfile <- function(filename, block_names) {
  temp_file <- readLines(filename)
  require(magrittr)
  
  # locate the two tables
  loc_table_trials <- stringr::str_detect(temp_file, "Trial")
  loc_table_trials <- c(1:length(loc_table_trials))[loc_table_trials]
  
  loc_table_RT <- stringr::str_detect(temp_file, "RT")
  loc_table_RT <- c(1:length(loc_table_RT))[loc_table_RT]
  
  loc_intro <- which(stringr::str_detect(temp_file, "intro_message") * 1 == 1)
  loc_end_practice <- which(stringr::str_detect(temp_file, "end_message") * 1 == 1)
  loc_break <- which(stringr::str_detect(temp_file, "break") * 1 == 1)
  loc_block <- sort(c(loc_intro,loc_end_practice, loc_break))
  
  for (i in 1:length(block_names)) {
    new_filename <- filename %>%
      stringr::str_replace(".log", paste0("_", block_names[i], ".log"))
    
    trials_starter <- loc_block[i]
    trials_end <- loc_block[i + 1]
    RT_start <- loc_block[i + length(block_names) + 1]
    RT_end <- loc_block[i + length(block_names) + 2]
    writing_text <- c(
      temp_file[1:3],
      temp_file[loc_table_trials], "",
      temp_file[trials_starter:trials_end], "",
      temp_file[loc_table_RT], "", "",
      temp_file[RT_start:RT_end]
    )
    writeLines(text = writing_text, con = new_filename)
  }
}

